services:
  blog-backend:
    build: "../blog-backend"
    ports:
      - "3500"
    container_name: blog-backend
    restart: always
  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=api.barabasakos.hu
      - EXTRA_DOMAINS=links.barabasakos.hu
      - VALIDATION=http
    volumes:
      - /home/aptalca/appdata/swag:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
  musicbot:
    build: "../MusicBot"
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
    container_name: musicbot
    restart: always
  links:
    build: "../url_shortener"
    ports:
      - "3600"
    container_name: links
    restart: always